# Web properties
server.port=8080

# Datasource properties
spring.datasource.url=jdbc:h2:mem:coursesdb
spring.datasource.username=sa
spring.datasource.password=

# H2 properties
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# SQL init setting for executing schema.sql
spring.sql.init.mode=always

# JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
