Web properties
server.port=8080

Datasource properties
spring.datasource.url=dbc:h2:mem:pony
spring.datasource.username=user
spring.datasource.password=password

 H2 properties
spring.h2.console.enabled=true
spring.h2.console.path=/h2

SQL init setting for executing schema.sql
spring.sql.init.mode=

JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=
spring.jpa.show-sql=
